import importlib.util,json
from pathlib import Path
import pytest
SCRIPT=Path(__file__).parents[1]/".agents/skills/deep-research/scripts/researchctl.py";spec=importlib.util.spec_from_file_location("researchctl_lifecycle",SCRIPT);module=importlib.util.module_from_spec(spec);assert spec.loader;spec.loader.exec_module(module)
def args(**values):return type("Args",(),values)()
def worker(run_id):return {"run_id":run_id,"status":"complete","question_id":"q-001","overlap_key":"fact","budget_profile":"lite","coverage_status":"sufficient","queries_run":["query"],"source_clusters":[],"source_attempts":[{"id":"src-1","url":"https://example.com/a","normalized_url":"https://example.com/a","status":"accepted","eligible_for_evidence":True,"tool":"direct_fetch","access_mode":"public_static","content_sha256":"a"*64}],"evidence_cards":[{"source_attempt_id":"src-1","source":{"url":"https://example.com/a","title":"A","publisher":"Example","source_type":"official"},"statement":"A fact","quote":"A fact","stance":"support","confidence":.8,"independence_group":"origin-a","prompt_injection_risk":"low","version_compatibility":"not_applicable"}],"rejected_sources":[],"contradictions":[],"gaps":[],"suggested_followups":[],"budget_used":{"tool_calls":1,"search_queries":1,"source_pages":1,"duration_minutes":1,"same_url_attempts_max":1,"output_reserve_ratio":.25,"estimated_input_tokens":1000,"estimated_output_tokens":200},"stop_reason":"acceptance_criteria_met"}
def test_full_lifecycle(tmp_path):
 module.WORKSPACE_ROOT=tmp_path;module.cmd_init(args(title="Topic",slug="topic",budget="lite",force=False,install_agent=False));module.cmd_plan(args(slug="topic",questions=1,force=False));module.cmd_run_start(args(slug="topic",mode="baseline"));root=tmp_path/"topic";run_id=json.loads((root/"state.json").read_text())["active_run_id"];wp=tmp_path/"worker.json";wp.write_text(json.dumps(worker(run_id)));module.cmd_ingest_worker(args(slug="topic",file=str(wp)));state=json.loads((root/"state.json").read_text());assert state["usage"]["queries"]==1 and state["usage"]["estimated_input_tokens"]==1000
 evidence_id=json.loads((root/"evidence/cards.jsonl").read_text().splitlines()[0])["id"];module.cmd_claim_create(args(slug="topic",text="A claim",confidence=.8,core=False));claim_id=next(iter(module.materialize(root/"claims.jsonl")));module.cmd_claim_link(args(slug="topic",claim=claim_id,evidence=evidence_id,stance="support",strength=.9));module.cmd_claim_status(args(slug="topic",claim=claim_id,status="supported",reason="evidence",approve_core=False))
 with pytest.raises(SystemExit,match="completion gate failed"):module.cmd_run_finish(args(slug="topic",status="complete",note=""))
 review={"review_id":"critic-1","run_id":run_id,"status":"complete","findings":[],"targeted_searches":[],"unresolved":[],"lesson_decisions":[],"completion_recommendation":"complete","stop_reason":"review_complete"};rp=tmp_path/"review.json";rp.write_text(json.dumps(review));module.cmd_critic_record(args(slug="topic",file=str(rp)));module.cmd_run_finish(args(slug="topic",status="complete",note="done"));reflection={"run_id":run_id,"critic_review_id":"critic-1","summary":"complete","open_questions":[],"next_actions":["monitor"],"lesson_candidates":[]};fp=tmp_path/"reflection.json";fp.write_text(json.dumps(reflection));module.cmd_reflect(args(slug="topic",file=str(fp)));assert json.loads((root/"state.json").read_text())["baseline_completed"]
def test_worker_run_id_must_match(tmp_path):
 module.WORKSPACE_ROOT=tmp_path;module.cmd_init(args(title="Topic",slug="topic",budget="lite",force=False,install_agent=False));module.cmd_run_start(args(slug="topic",mode="baseline"));path=tmp_path/"worker.json";path.write_text(json.dumps(worker("wrong-run")))
 with pytest.raises(SystemExit,match="does not match"):module.cmd_ingest_worker(args(slug="topic",file=str(path)))
